    SELECT 
        V.DOCUMENTO AS FATURA,
        V.FECHA AS DATA,
        V.TIPO_DOCUMENTO AS 'TIPO DOCUMENTO',
        CONCAT(C.NOMBRE, ' ', C.APELLIDO) AS CLIENTE,
        CONCAT(VE.NOMBRE,'',VE.APELLIDO) AS VENDEDOR,
        C.ESTADO_CIVIL AS 'ESTADO CIVIL CLIENTE',
        C.EDAD AS IDADE_CLIENTE,
        A.NOMBRE AS PRODUTO,
        A.FAMILIA,
        D.CANTIDAD AS QUANTIDADE,
        D.PRECIO_UNITARIO AS PRECO_UNITARIO,
        V.IMPUESTO AS IMPOSTO,
        S.NOMBRE_SUCURSAL AS FILIAL,
        CO.COMUNA_NOMBRE AS COMUNIDADE_FILIAL,
        P.PROVINCIA_NOMBRE AS PROVINCIAL_FILIAL,
        R.REGION AS REGION_FILIAL,
        DATENAME(month, FECHA) AS NOME_MES,
        DATEPART(DAY,   FECHA) AS DIA,
        DATENAME(WEEKDAY, FECHA) AS DIA_SEMANA,
        DATEPART(MONTH, FECHA) AS MES_NUMERO,
        DATEPART(YEAR,  FECHA) AS ANO
    FROM 
        VENTAS AS V 
        LEFT JOIN DETALLE_VENTA AS D ON V.DOCUMENTO = D.DOCUMENTO
        LEFT JOIN VENDEDORES    AS VE ON VE.ID_VENDEDOR = V.ID_VENDEDOR
        LEFT JOIN CLIENTES      AS C ON C.ID_CLIENTE = V.ID_CLIENTE
        LEFT JOIN SUCURSAL      AS S ON S.SUCURSAL_ID = V.SUCURSAL_ID
        LEFT JOIN ARTICULOS     AS A ON A.CODIGO_PRODUCTO = D.CODIGO_PRODUCTO
        LEFT JOIN COMUNA        AS CO ON CO.COMUNA_ID = S.COMUNA_ID
        LEFT JOIN PROVINCIA     AS P ON P.PROVINCIA_ID = CO.PROVINCIA_ID
        LEFT JOIN REGION        AS R ON R.REGION_ID = P.REGION_ID
    WHERE
        YEAR (V.FECHA) = 2025 AND MONTH (V.FECHA) = 8;